import './assets/scss/index.scss';
import dayjs from 'dayjs';
import customParseFormat from 'dayjs/plugin/customParseFormat';
import utc from 'dayjs/plugin/utc';

export { default as Button } from './components/Button';
export { default as IconButton } from './components/IconButton';
export { default as Container } from './components/Container';
export { default as Text } from './components/Text';
export { default as TextInput } from './components/TextInput';
export { default as InputLabel } from './components/InputLabel';
export { default as Autocomplete } from './components/Autocomplete';
export { default as DateInput } from './components/DateInput';
export { default as Steps } from './components/Steps';
export { default as CheckboxInput } from './components/CheckboxInput';
export { default as RadioInput } from './components/RadioInput';
export { default as Navigation } from './components/Navigation';
export { default as Pagination } from './components/Pagination';
export { default as Paper } from './components/Paper';
export { default as Condition } from './components/Condition';
export { default as Loader } from './components/Loader';
export { default as Chip } from './components/Chip';
export { default as Divider } from './components/Divider';
export { default as Dialog } from './components/Dialog';
export { default as AlertDialog } from './components/AlertDialog';
export { default as ScrollSpy } from './components/ScrollSpy';
export { default as SwitchInput } from './components/SwitchInput';
export { default as TextAreaInput } from './components/TextAreaInput';
export { default as BottomActionBar } from './components/BottomActionBar';
export { default as FileUpload } from './components/FileUpload';
export { default as FileItemView } from './components/FileItemView';
export { default as ProgressBar } from './components/ProgressBar';
export { default as Table } from './components/Table';
export { default as ChipReach } from './components/ChipReach';
export { default as ChipAbsolute } from './components/ChipAbsolute';
export { default as Tabs } from './components/Tabs';
export { default as PopoverToggler } from './components/PopoverToggler';

export * from './components/icons';
export * from './hooks';

dayjs.extend(customParseFormat);
dayjs.extend(utc, {});
